chore: Move Puck styles to a separate shadow DOM tree
shirakaba/10ten-ja-reader pull request #2
Opened 2021-06-29 09:36 UTC by birtles

This is a revision of #1 that uses two shadow DOM trees instead of 2

2021-06-30 23:27 UTC, shirakaba requested changes
Looks great! Let’s go with two shadow trees. Good idea about stopping mousemove events propagating from the puck. Thanks for doing the necessary refactor! Hoping to get some time to get back to the code over the weekend.

2021-06-30 23:27 UTC, shirakaba commented on src/puck.ts
> +    removeContentContainer('tenten-ja-puck');
It’s not the end of the world, but we’re still holding a reference to `this.puck` which we’ll never use again (it’s reassigned on render()), preventing its container from being garbage-collected, so we might as well assign `this.puck = null` in here.

2021-07-01 01:47 UTC, birtles commented on src/puck.ts
> +    removeContentContainer('tenten-ja-puck');
Sure! This should be fixed now.

2021-07-01 08:25 UTC, shirakaba approved these changes

2021-07-01 08:26 UTC, shirakaba commented
@birtles You’re welcome to merge at your convenience!

2021-07-01 08:29 UTC, merged