feat: Popup avoids the mouse event, earth and moon, and the safe area
shirakaba/10ten-ja-reader pull request #8
Opened 2021-08-01 21:46 UTC by shirakaba

# New layout behaviour

To support the safe area and avoid the puck, I've ended up rewriting the layout code , and it's now much more powerful. It:

* avoids the safe area (though this behaviour is currently only enabled when the puck is in use, as it's the puck that monitors the safe area);
* avoids the puck (for puck users) or the mouse (for mouse users);
* avoids the tooltip as before (for mouse users);
* ensures that the popup is constrained to the viewport, rather than its old behaviour of letting it extend out of the viewport in the "block" direction (i.e. left/right positioned popups used to extend downward, and top/bottom positioned popups used to extend rightward);
* calculates the "best" popup position by assessing all directions and choosing the one with the least clipping, whilst still preferring orthogonal placement to the text direction where possible.

Solves some clipping issues seen in https://github.com/birchill/10ten-ja-reader/issues/690#issuecomment-890530897.

2021-08-02 02:29 UTC, birtles requested changes
Thanks so much for this. It's very thorough and I'm sure it works great.

I've left a number of comments but overall I'd like to find ways to simplify this further. I've left some ideas there but I'll try to have a fiddle too and see what I discover.

2021-08-02 02:29 UTC, birtles commented on src/puck.ts
> +          : minorVerticalPortionOfPuckAboutMouseEvent,
I wonder if we really need to worry about the moon height here? For the `puckAboveMouseEvent` / `puckBelowMouseEvent` members I think simply returning a vertical clearance member that is negative for above, or positive for below would be enough and would allow combining these into one value.

We could likely do something similar for the horizontal values but make it a scalar instead?

2021-08-02 02:29 UTC, birtles commented on src/puck.ts
> +      moonWidth: this.moonWidth,
It looks like we don't use these three members so can we drop them?

2021-08-02 04:04 UTC, birtles commented
Just having a fiddle with this now, I think we need to work harder to constrain the width.

For example using v1.2 we position the popup to the side here:

![image](https://user-images.githubusercontent.com/1232595/127802678-e4c90812-14f2-4462-b247-b73d042256b5.png)

but with these patches we push it to the top and crop it:

![image](https://user-images.githubusercontent.com/1232595/127802708-c70162fc-cf57-4841-b793-d7e0155c5f45.png)

That, I guess, it because we detect the width of the puck and try to avoid it. Instead, however, we should just constrain the width to the available space there and apply `max-width` to the popup so it fits there.

On an iPhone positioning to the side is rarely going to be that useful but it could make a significant difference to useability on an iPad.

2021-08-02 06:48 UTC, shirakaba commented
Thanks for the review! I’ll get back to the other comments later, but just a quick one:

> I think we need to work harder to constrain the width.

We can change the sorting algorithm to prefer placing it on the left, and the width will be constrained just fine, but it will clip even in v1.2 if the tabs are on the top (as is the default):

https://github.com/birchill/10ten-ja-reader/issues/690#issuecomment-890591780

2021-08-02 06:53 UTC, birtles commented
> We can change the sorting algorithm to prefer placing it on the left, and the width will be constrained just fine, but it will clip even in v1.2 if the tabs are on the top (as is the default), as shown in the first two screenshots:

Right, what I mean is not that the sorting is wrong, but that we should probably make that popup not clip in that case. That is, even before this change, we should make that popup switch to flexible layout in that case.

2021-08-02 06:56 UTC, birtles commented
So I realise that was a whole lot of rambling review comments so I went ahead and tried to apply the suggested changes myself.

I've pushed a whole bunch of patches to the [`popup-positioning-tweaks` branch](https://github.com/shirakaba/10ten-ja-reader/commits/popup-positioning-tweaks) that hopefully illustrates what I had in mind.

2021-08-02 09:00 UTC, shirakaba commented
> So I realise that was a whole lot of rambling review comments so I went ahead and tried to apply the suggested changes myself.
> 
> I've pushed a whole bunch of patches to the [`popup-positioning-tweaks` branch](https://github.com/shirakaba/10ten-ja-reader/commits/popup-positioning-tweaks) that hopefully illustrates what I had in mind.

Thanks so much for refactor! I've had a look over it, and it looks brilliant.

## `content.ts`

Good idea to pull the puck internals up a level so that `popup-position.ts` doesn't need to know about it. `cursorClearance` is a great abstraction. I was confused by the typing of it, though (it's not a set of insets – I guess it's margin). Perhaps we should rename the type `SafeAreaInsets` to the more general-purpose `Position` and move it to a file other than `puck.ts`.

It also looks like I accidentally left a FIXME in there, which can be removed as it has now been addressed:

```
// FIXME: make popup avoid earth, moon (this.currentPoint - which may be
// above or below the earth), thumb, and maybe safe area (we don't want it
// slipping under notch - though is that even possible?).  So at the very
// least, make an exclusion zone around the moon (this.currentPoint) and
// earth.
```

## `popup.ts`

 I couldn't work out the general case during the implementation, and this cleanup nails it. The equations all look correct. Good idea to return `undefined` rather than bothering with a 1px-thick popup in the worst cases. The one difference I would note is that, when positioning the popup above/below, I calculated `idealX` as (assuming these variables are in scope):

```diff
- const idealX = target.x;
+ const idealX = target.x - hasPuck ? moonWidth / 2 : 0;
```

This makes the left of the popup line up with the left of the moon, which looked a bit more aesthetic to me in practice. But it's debatable (lining up with the touch point is logical in itself).

---

Off to work now – gotta go!

2021-08-02 09:17 UTC, birtles commented
> > So I realise that was a whole lot of rambling review comments so I went ahead and tried to apply the suggested changes myself.
> > I've pushed a whole bunch of patches to the [`popup-positioning-tweaks` branch](https://github.com/shirakaba/10ten-ja-reader/commits/popup-positioning-tweaks) that hopefully illustrates what I had in mind.
> 
> Thanks so much for refactor! I've had a look over it, and it looks brilliant.

Thank you!

> ## `content.ts`
> 
> Good idea to pull the puck internals up a level so that `popup-position.ts` doesn't need to know about it. `cursorClearance` is a great abstraction. I was confused by the typing of it, though (it's not a set of insets – I guess it's margin). Perhaps we should rename the type `SafeAreaInsets` to the more general-purpose `Position` and move it to a file other than `puck.ts`.

Yes, definitely!

> It also looks like I accidentally left a FIXME in there, which can be removed as it has now been addressed:
> 
> ```
> // FIXME: make popup avoid earth, moon (this.currentPoint - which may be
> // above or below the earth), thumb, and maybe safe area (we don't want it
> // slipping under notch - though is that even possible?).  So at the very
> // least, make an exclusion zone around the moon (this.currentPoint) and
> // earth.
> ```

Ah, I wondered about that! I thought it had been addressed but wasn't sure if there was still more work to do.

> ## `popup.ts`
> 
> I couldn't work out the general case during the implementation, and this cleanup nails it. The equations all look correct. Good idea to return `undefined` rather than bothering with a 1px-thick popup in the worst cases.

Yeah, I was trying to work out what the correct behaviour should be there and I think just eliminating that position as a possibility is the way to go.

We possibly need to handle the case when _all_ the positions end up being undefined and return something sensible in that case but hopefully that never happens?

> The one difference I would note is that, when positioning the popup above/below, I calculated `idealX` as (assuming these variables are in scope):
> 
> ```diff
> - const idealX = target.x;
> + const idealX = target.x - hasPuck ? moonWidth / 2 : 0;
> ```
> 
> This makes the left of the popup line up with the left of the moon, which looked a bit more aesthetic to me in practice. But it's debatable (lining up with the touch point is logical in itself).

Yes, I dropped that just because it made it harder to drop the dependency on the puck in the positioning code.

Also, I noticed that even though we initially align the top of the pop-up with the moon, you can still move the moon and the popup doesn't update so the alignment is lost.

If it's important to have that initial alignment then I guess we need to think of a suitable abstraction for that concept (`targetVerticalAlignOffset`? i.e. the offset we add when aligning the popup with the target vertically?).

> Off to work now – gotta go!

Thanks for following up!

2021-08-02 10:06 UTC, shirakaba commented
> We possibly need to handle the case when all the positions end up being undefined and return something sensible in that case but hopefully that never happens?

Keeps me awake at night. 10ten Japanese Reader running on Apple Watch... Though to be fair, I did notice that iOS Safari bafflingly makes the popup text (and thus the popup width itself) larger in landscape mode, so there may well be unsolvable layouts on iPhone SE in landscape.

I think in that situation, when there's no ideal layout, simply go with the solution that's easiest to write. Maybe just fall back to top-left layout. Feels less jarring than showing no popup at all.

> Yes, I dropped that just because it made it harder to drop the dependency on the puck in the positioning code.
> 
> Also, I noticed that even though we initially align the top of the pop-up with the moon, you can still move the moon and the popup doesn't update so the alignment is lost.
> 
> If it's important to have that initial alignment then I guess we need to think of a suitable abstraction for that concept (`targetVerticalAlignOffset`? i.e. the offset we add when aligning the popup with the target vertically?).

True, in practice the moon moves sufficiently far when being brought to rest that the effort may be irrelevant. Indeed if we can think of the right abstraction for it, then there's probably more justification to implement it. Will mull it over later.

2021-08-02 20:51 UTC, shirakaba commented
Away from my desk now, but just to confirm that I’d be very happy for your branch to be merged into this PR as-is!

2021-08-03 01:16 UTC, birtles commented
> Keeps me awake at night. 10ten Japanese Reader running on Apple Watch... Though to be fair, I did notice that iOS Safari bafflingly makes the popup text (and thus the popup width itself) larger in landscape mode, so there may well be unsolvable layouts on iPhone SE in landscape.
> 
> I think in that situation, when there's no ideal layout, simply go with the solution that's easiest to write. Maybe just fall back to top-left layout. Feels less jarring than showing no popup at all.

Sounds great. I've added a patch for that now.

2021-08-03 01:30 UTC, birtles commented
> Away from my desk now, but just to confirm that I’d be very happy for your branch to be merged into this PR as-is!

Thanks! I've merged my changes in now.

I think this is strictly an improvement over what we have so far so we could merge this into `feat/puck` now.

A few improvements we might like to make, however, are:

- [ ] Create a suitable type for the `cursorClearance` member rather than abusing `SafeAreaInsets`.

- [ ] When we decide _not_ to position above/or below, but go to the _right_ side instead, ideally we should add the bounding box of the selected text to the cursor clearance. Otherwise we end up with the popup overlapping the text.

   e.g.
   ![image](https://user-images.githubusercontent.com/1232595/127942759-229dba4f-18ac-43c9-bbb7-db26620dbe3e.png)

   I think that would be a matter of getting the appropriate `Range` object then perhaps taking the union of just the first `Rect` returned by `getClientRects` and the existing `cursorClearance` rect. The reason being that if the range spans a line break then `getBoundingClientRect` will return a massive region -- and if we use that as the `cursorClearance` rect we'll have a hard time positioning the popup!

- [ ] As discussed in https://github.com/birchill/10ten-ja-reader/issues/690, it would be nice if we could somehow evaluate popup size in the absence of any fixed width. I can't see how we can do that without triggering multiple reflows, however, so maybe instead we can simply make sure that when we constrain the width, it doesn't have those ugly scrollbars showing (I guess it should just overlap the cursor in that case?)

2021-08-03 03:40 UTC, birtles commented
I got nerd-sniped on this so I ended up tackling the first two issues from above.

2021-08-03 04:17 UTC, birtles commented
I ended up addressing the third point (for now anyway) in https://github.com/birchill/10ten-ja-reader/commit/7cd657c997a192f5cd9cb918ed52a8c3c3755838 so once we rebase that should be covered too.

2021-08-04 14:02 UTC, shirakaba commented
> I think this is strictly an improvement over what we have so far so we could merge this into `feat/puck` now.

Agreed! I'd like to get that `targetVerticalAlignOffset` (or similar) concept in otherwise it's going to bug me, but after that, I'll get this merged.

Thanks a ton for identifying and solving those three issues! The text selection box is a great touch, and I'm really glad for your https://github.com/birchill/10ten-ja-reader/commit/7cd657c997a192f5cd9cb918ed52a8c3c3755838 fix, as it makes it the left/right popups viable in far more cases.

2021-08-04 14:04 UTC, shirakaba commented on src/geometry.ts
> +};
@birtles Is there a reason for the redundancy with Rect here? I'm guessing for potentially better Intellisense, but if not, we might as well alias these.

```suggestion
/// Measures from some box (or point) outwards
export type MarginBox = Rect;

/// Measures from some box inwards
export type PaddingBox = Rect;
```

2021-08-04 14:47 UTC, shirakaba commented on src/content.ts
> +  let puck: RikaiPuck | null = null;
Although you've already addressed the cleanup aspect, I've added a commit to address the initialisation aspect: https://github.com/shirakaba/10ten-ja-reader/pull/8/commits/fe2458fe3a50fd8c164ae31283f0a61f1ed7d162.

2021-08-04 14:48 UTC, shirakaba commented on src/popup-position.ts
> +  // use, but in future we may want to turn it on for mouse users as well.
Makes sense!

2021-08-04 14:49 UTC, shirakaba commented on src/popup-position.ts
> +  puck: RikaiPuck | null;
You've solved this now; thanks!

2021-08-04 14:52 UTC, shirakaba commented on src/popup-position.ts
> +  //   getViewportDimensions() function, for more details.
Agreed we should respect them regardless – it's just that currently the only insight we have into safe area is via the puck instance, which monitors it.

The TODO in content.ts acknowledges this. I think it may be out of scope for this immediate PR (and non-critical for the short-term, as it's mainly devices that one would use a puck on – touch devices – that have non-zero safe area insets in the first place).

```js
// TODO: Make this get the safe area even when we're not using the puck.
```

2021-08-04 15:22 UTC, shirakaba commented on src/popup-position.ts
> +      safeAreaInsets = puck.getSafeArea(puckSafeAreaProvider);
Thanks for resolving this!

2021-08-04 15:24 UTC, shirakaba commented on src/popup-position.ts
> +  function placePopupAbove(): PopupPosition {
Thanks for refactoring this!

2021-08-04 15:24 UTC, shirakaba commented on src/puck.ts
> +    // const restOffsetY = Math.cos(angle) * 25 * offsetYOrientationFactor;
Sure thing.

2021-08-04 15:31 UTC, shirakaba commented on src/popup-position.ts
> +      puck.invalidateCachedViewportDimensions();
Thanks for addressing the `puckSafeAreaProvider` bit. I've addressed the `flush` bit in: https://github.com/shirakaba/10ten-ja-reader/pull/8/commits/410c10a2c01c045c87b0b6e009b285b8a618d15c

2021-08-04 15:31 UTC, shirakaba commented on src/popup-position.ts
> +  function placePopupToLeft(): PopupPosition {
Thanks for resolving this with your refactor.

2021-08-04 15:34 UTC, shirakaba commented on src/popup-position.ts
> +  const marginToPopupForPuckUsers = 25;
Resolved in your refactor.

2021-08-04 15:35 UTC, shirakaba commented on src/puck.ts
> +      moonWidth: this.moonWidth,
Resolved in your refactor. We might need to bring back `moonWidth` and `moonHeight` though, for realigning the popup to the top-left corner of the puck (rather than the mouse event).

2021-08-04 15:45 UTC, shirakaba commented on src/puck.ts
> +          : minorVerticalPortionOfPuckAboutMouseEvent,
Of course the moon height is only 10 px so there's not much to it, but it's partially about future-proofing (e.g. what if the moon size needs to be increased for accessibility reasons).

As for combining the values, I'm not totally following. Does it rely on the assumption that the puck's above and below orientations will be mirror images? Just that this won't be the case, as the moon juts out further in the "below" orientation. Or would the idea be to expose `minorVerticalPortionOfPuckAboutMouseEvent` and `majorVerticalPortionOfPuckAboutMouseEvent` directly instead of `puckAboveMouseEvent` and `puckBelowMouseEvent`? If the latter, mainly I think it might be simpler to consume these values in their current format of having explicit positional names.

Happy to review, though, if you'd show what you'd have in mind.

2021-08-04 16:34 UTC, shirakaba commented
> Agreed! I'd like to get that `targetVerticalAlignOffset` (or similar) concept in otherwise it's going to bug me, but after that, I'll get this merged.

I've thought about this a bit and I'm not totally convinced that aligning to the top-left corner of the moon is any more logical than aligning to its centre, so I'm happy to leave it unimplemented. As for getting this merged, You'll see I've found a need to add a few more commits to address some of the pending comments on the PR.

One thing remains to decide on, based on the conversation here: https://github.com/birchill/10ten-ja-reader/issues/690#issuecomment-890624757

>> From the layout code, it's clear that the popup extending offscreen is intentional, but I think it would be better for it to remain within the viewport and be scrollable. We've touched base on this subject before and it sounded like the popup being scrollable would be desirable.
>
> Right, that's intentional because:
>
> (a) when you're using a mouse, you can't scroll the popup, but
> (b) you can use the mouse wheel to scroll the page and see the rest of the popup (the popup doesn't update on scroll events)

The original layout code allowed for popups that were placed:

– ... left/right to extend downward offscreen.
– ... above/below to extend rightward offscreen.

In this PR, we currently clip the popup to the viewport, whether you're using the puck or the mouse. As of https://github.com/shirakaba/10ten-ja-reader/pull/8/commits/aa279e3ea9a27a5660137042c947caf20e91583e, we can now distinguish mouse events from the puck versus the mouse, so can revisit this.

1) Do we want to continue clipping the popup to the viewport for puck users? I think this UX would be preferable for touchscreen users, but if so, we will need to set `overflow: scroll` on the right part of the popup.

2) Presumably we want to restore the original behaviour of allowing the popup to extend offscreen for non-puck users?

2021-08-04 23:19 UTC, birtles commented on src/geometry.ts
> +};
I think the only difference is that `Rect` uses `width`/`height` whereas the two boxes use `bottom`/`right`. We could definitely alias, e.g. `PaddingBox` to `MarginBox` though or just conflate them into one.

(`DOMRect` actually has both `width`/`height` and `bottom`/`right` from memory but it uses `bottom`/`right` in a different way to us.)

2021-08-04 23:29 UTC, birtles commented
> I've thought about this a bit and I'm not totally convinced that aligning to the top-left corner of the moon is any more logical than aligning to its centre, so I'm happy to leave it unimplemented. As for getting this merged, You'll see I've found a need to add a few more commits to address some of the pending comments on the PR.

Thanks!

I wasn't quite sure about the first patch, but I think we'll end up reworking that lifecycle part anyway when we cover the enabling/disabling functionality so we can revisit it there if necessary.

As for the second patch, I'm curious if the flushing is actually needed? I couldn't see why it would be. If it is, perhaps we should actually clear the cached value and then update it inside `getSafeArea()`?

> In this PR, we currently clip the popup to the viewport, whether you're using the puck or the mouse. As of [aa279e3](https://github.com/shirakaba/10ten-ja-reader/commit/aa279e3ea9a27a5660137042c947caf20e91583e), we can now distinguish mouse events from the puck versus the mouse, so can revisit this.

Excellent, I've been looking forward to introducing that distinction.

>     1. Do we want to continue clipping the popup to the viewport for puck users? I think this UX would be preferable for touchscreen users, but if so, we will need to set `overflow: scroll` on the right part of the popup.

Yes, I agree. For touchscreen users, clip and `overflow: scroll`, for non-touchscreen users, don't constrain the height if the position is below. (If the position is above, we still want to clip it so it doesn't overlap the mouse. If the position is left/right, hopefully the changes to make the content responsive to the changed width will mean that constraining the width is ok in most cases.)

>     2. Presumably we want to restore the original behaviour of allowing the popup to extend offscreen for non-puck users?

Yes, agreed.

2021-08-04 23:30 UTC, birtles approved these changes

2021-08-04 23:35 UTC, birtles commented
I wonder if we should make ef2d35ca8dfa811935d91512f5788e1d8903c1a9 as separate PR/patch series?

There's a bit of other work we should do in response to that distinction (e.g. not requiring hold keys to be pressed etc.) and we might decide it's simpler to just call straight into the `ContentHandler` without going through the event dispatch machinery.

2021-08-05 00:31 UTC, shirakaba commented
> I wonder if we should make ef2d35c as separate PR/patch series?

If there’s more to do, then sure, we can extract it out of this PR.

> I wasn't quite sure about the first patch, but I think we'll end up reworking that lifecycle part anyway when we cover the enabling/disabling functionality so we can revisit it there if necessary.

No problem, happy for it to be reworked.

> As for the second patch, I'm curious if the flushing is actually needed? I couldn't see why it would be. If it is, perhaps we should actually clear the cached value and then update it inside getSafeArea()?

I think I introduced it because I ran into a case where it was needed. On iOS 15, this might be the case if safe area insets happen to update more frequently than corresponding "resize" events are fired, for example (this is only speculation). I’ll have to check again. As for the second part, I’d thought that my commit does invalidate the cached value and update it, but maybe I missed something.

2021-08-05 21:21 UTC, shirakaba commented
> I wonder if we should make [ef2d35c](https://github.com/shirakaba/10ten-ja-reader/commit/ef2d35ca8dfa811935d91512f5788e1d8903c1a9) as separate PR/patch series?

Now separated out into the branch `distinguish-puck-events`. I haven't opened it as a PR yet, as I think we're pretty close to merging this current PR into `feat/puck`.

2021-08-05 22:06 UTC, shirakaba commented
> > I think I introduced it because I ran into a case where it was needed. On iOS 15, this might be the case if safe area insets happen to update more frequently than corresponding "resize" events are fired, for example (this is only speculation). I’ll have to check again.
> 
> Ok, that makes sense. Perhaps we should add a comment so we know why we need to flush in that case.

I've done a bit of experimenting with the Web Inspector. The window `resize` event does seem to be reliable for tracking safe area changes, though doesn't track changes to the insets as rapidly as a 1 ms interval would. It will typically fire around 16 times as the safe area animates in/out, though it varies wildly depending on how congested the main thread is (e.g. whether you have a 1 ms interval running at the same time, or are doing a pan gesture, or have a debugger attached).

Probably the best thing for me to do is to have another go at using the puck and seeing how it handles without flushing the reading of the safe area insets, in case I've merely misremembered and gone into superstition.

2021-08-05 22:16 UTC, shirakaba commented on src/geometry.ts
> +};
Oh whoops, I misread `Rect`. How about this, then:

```suggestion
export type Box = {
  top: number;
  right: number;
  bottom: number;
  left: number;
};

/// Measures from some box (or point) outwards
export type MarginBox = Box;

/// Measures from some box inwards
export type PaddingBox = Box;
```

2021-08-05 23:11 UTC, birtles commented
> I've done a bit of experimenting with the Web Inspector. The window `resize` event does seem to be reliable for tracking safe area changes, though doesn't track changes to the insets as rapidly as a 1 ms interval would. It will typically fire around 16 times as the safe area animates in/out, though it varies wildly depending on how congested the main thread is (e.g. whether you have a 1 ms interval running at the same time, or are doing a pan gesture, or have a debugger attached).

16 times for the whole animation seems more that sufficient? Typically the animation on screen should only be updating once every 16ms or so.

> Probably the best thing for me to do is to have another go at using the puck and seeing how it handles without flushing the reading of the safe area insets, in case I've merely misremembered and gone into superstition.

Yes, that sounds best.

2021-08-05 23:11 UTC, birtles commented
> Now separated out into the branch `distinguish-puck-events`. I haven't opened it as a PR yet, as I think we're pretty close to merging this current PR into `feat/puck`.

Thanks! Yes, feel free to merge this whenever you're ready!

2021-08-07 10:52 UTC, shirakaba commented
Looks like we need to use `document.defaultView.innerWidth` for the left and right safe area insets as well, because otherwise you can't look up any text towards the left and right sides of the screen in landscape mode:

https://user-images.githubusercontent.com/14055146/128597668-e92315ad-537a-4b52-8f81-6304d9d680cb.mp4

I'll address that now.

2021-08-07 10:59 UTC, shirakaba commented
# Justification for flushing the safe area

Here are two cases I caught **having turned off** the flushing of the safe area insets cache. This was with the debugger attached, though, so the event-handling might not be as rapid as usual. I'll try without the debugger attached to see if it still reproduces.

<table>
<tr>
<td>Popup extending underneath URL bar</td>
<td>Popup constrained too short</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/14055146/128597862-337b3cdf-3ead-4bcd-9468-ce5bb54342c8.PNG" width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/14055146/128597860-ff6acb90-f56b-4c5f-8000-d17c04c74055.PNG" width="300"/></td>
</tr>
</table>

2021-08-07 12:49 UTC, shirakaba commented
> Keeping the puck bound to the safe area while dragging is a harder problem to solve – I had originally solved it by checking the safe area on every pointer move event (which my iPhone 11 Pro seems perfectly happy to handle), but that approach may theoretically choke low-end Android devices. Hard to know without trying.

The only way I can think to keep an up-to-date safe area (i.e. even whilst dragging, which is when window "resize" events are suppressed) is if we, for browsers that support `ResizeObserver`, insert into the DOM an invisible element that adheres exactly to the safe area, then monitor that for resize events. It might be worth a try.

2021-08-07 19:13 UTC, shirakaba commented
I'll merge this into `feat/puck` now as, as you say, this is already a step forward. I'll clarify pending issues in the `feat/puck` thread.

2021-08-07 19:13 UTC, merged